---
# icinga2_server/tasks/main.yml

- name: 'Load variables'
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', parameters) }}"
  vars:
    parameters:
      files:
        - "vars_{{ ansible_distribution | regex_replace(' ', '_') }}_{{ ansible_distribution_version }}.yml"
        - "vars_{{ ansible_distribution | regex_replace(' ', '_') }}_{{ ansible_distribution_major_version }}.yml"
        - "vars_{{ ansible_distribution | regex_replace(' ', '_') }}.yml"
        - "vars_{{ ansible_os_family | regex_replace(' ', '_') }}.yml"
      paths:
        - ../vars/

#
# Icinga2 server
#
- name: 'Install the icinga2 package'
  ansible.builtin.package:
    name: "{{ icinga2_server_package_name }}"
    update_cache: true

- name: 'Enable the API'
  ansible.builtin.command:
    cmd: 'icinga2 api setup'
    creates: '/etc/icinga2/conf.d/api-users.conf'
  notify:
    - 'Restart the icinga2 service'

- name: 'Enable the icinga2 service'
  ansible.builtin.service:
    name: "{{ icinga2_server_service_name }}"
    enabled: true

- name: 'Start the icinga2 service'
  ansible.builtin.service:
    name: "{{ icinga2_server_service_name }}"
    state: 'started'

#
# Icinga2 web
#
- name: 'Install the icinga2-web package'
  ansible.builtin.package:
    name: "{{ icinga2_web_package_name }}"
    update_cache: true

#
# monitoring plugins
#
- name: 'Install the monitoring-plugins package'
  ansible.builtin.package:
    name: "{{ monitoring_plugins_package_name }}"
    update_cache: true
