---
# icinga2_server/handlers/main.yml

- name: 'Restart the icinga2 service'
  ansible.builtin.service:
    name: "{{ icinga2_server_service_name }}"
    state: 'restarted'

- name: 'Restart the icinga2 web service'
  ansible.builtin.service:
    name: "{{ icinga2_web_service_name }}"
    state: 'restarted'
